###
# 쿠폰 발급
POST http://localhost:8081/coupon/issued
Content-Type: application/json

{
    "userId": "user_16",
    "key": "coupon:time-attack:1:date-time:1:issued:users"
}

###
# 쿠폰 리스트 보기
GET http://localhost:8081/coupon

###
